
#登陆
POST http://localhost:8080/control/authentication/login?username=admin&password=888888
#POST http://localhost:9595/login?username=123123123&password=312312312123
Accept: */*
Cache-Control: no-cache

###



#密码模式（resource owner password credentials）
POST http://jie:jbkj@172.20.0.156:9595/oauth/token?username=root&password=root&grant_type=password&scope= app
Accept: */*
Cache-Control: no-cache

###
#密码模式（resource owner password credentials）
POST http://jie:jbkj@localhost:8080/oauth/token?username=root&password=root&grant_type=password&scope=app ROLE_SUPER_ADMIN
Set-Cookie: JSESSIONID=05070E8E7AAD5287D9A2E01264AB5452;
Accept: */*
Cache-Control: no-cache

<> 2019-06-11T014319.200.json
<> 2019-06-11T013916.200.json
<> 2019-06-11T013543.200.json
<> 2019-06-11T011007.200.json
<> 2019-06-11T010224.200.json

###


# 客户端模式（client credentials）
POST http://jie:jbkj@localhost:8080/oauth/token?grant_type=client_credentials&scope=app test
Accept: */*
Cache-Control: no-cache

<> 2019-06-11T014726.200.json

###


#授权码
#在浏览输入：
http://172.20.0.156:8080/oauth/authorize?client_id=jie&response_type=code&redirect_uri=http://172.20.0.156:8090/

<> 2019-06-11T014800.200.html
<> 2019-06-11T012510.200.html

###

#通过code获取access_token与fresh_token
POST http://jie:jbkj@localhost:8080/oauth/token?redirect_uri=http://localhost:8090/&grant_type=authorization_code&code=t9navd
Accept: */*
Cache-Control: no-cache

<> 2019-06-11T014839.200.json
<> 2019-06-11T014812.400.json

###

#浏览器中输入：直接获取access_token
GET http://localhost:8080/oauth/authorize?client_id=jie&response_type=token&redirect_uri=http://localhost:8090/

###
#获取OAuth2客户信息
GET http://localhost:8080/user?access_token=0f08846e-d727-4370-8afb-4d802c30e458
Accept: */*
Cache-Control: no-cache

###

#通过refresh_token获取access_token与refresh_token
POST http://jie:jbkj@localhost:8080/oauth/token?refresh_token=52c1ddf6-4b35-4ba7-95e0-03b7f74f3928&grant_type=refresh_token&scope=app test
Accept: */*
Cache-Control: no-cache

###